### ISSUE TITLE
Add Trojan communication features

### ISSUE THREAD

**Issue by socmap** [ChrisTruncer/Egress-Assess#48]
I am a Chinese security researcher, very happy to use Egress-assessment, I would like to add gh0st Trojan simulation traffic, how to simulate the implementation?

**Comment by ChrisTruncer** [comment]
You will need to run the malware in a VM, capture its traffic, and create
network indicators based on its traffic. Then submit those to Egress-Assess
in a pull request.


-----------------------------------------------------------------------------------------
Christopher Truncer
@christruncer <http://www.twitter.com/christruncer>

On June 9, 2017 at 2:33:56 AM, socmap (notifications@github.com) wrote:

I am a Chinese security researcher, very happy to use Egress-assessment, I
would like to add gh0st Trojan simulation traffic, how to simulate the
implementation?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChrisTruncer/Egress-Assess/issues/48>, or mute the
thread
